%% 建立一个包含控件的图形用户界面
% 点击控件时执行该控件的相应功能
% 要求绘制membrane，peaks和sphere函数图形
% 并有光照控制效果。

%% 建立图形窗口和坐标轴，去除窗口本身的菜单条和工具条，并命名为  mysecondGUI
h0=figure('menubar','none','toolbar','none','position',[198 56 408 468],'name','Figure GUI');
h1=axes('parent',h0,'position',[0.15 0.45 0.7 0.5],'visible','off');

%% 建立静态文本框和动态文本框
htext1=uicontrol('parent',h0,'units','points','position',[54 110 45 15],'string','Please Input Title','style','text');
hedit=uicontrol('parent',h0,'units','points','position',[100 110 45 16],'callback','title(get(hedit,''string''))','style','edit');

%% 创建三个按钮
hbutton1=uicontrol('parent',h0,'units','points','string','Sphere',...    
                   'position',[20 65 50 18],'callback','surf(sphere);axis tight');

hbutton2=uicontrol('parent',h0,'units','points','string','Membrane',...    
                   'position',[75 65 50 18],'callback','surf(membrane);axis tight');

hbutton3=uicontrol('parent',h0,'units','points','string','Sinc','position',[135 65 50 18],'callback',...
                   ['[x,y]=meshgrid(-5:0.5:5);','r=sqrt(x.^2+y.^2)+eps;',...
                   'z=sin(r)./r;','surf(x,y,z)']);

%% 创建静态文本框和滚动条，鼠标拖动滚动条控制图形的颜色变化
htext2=uicontrol('parent',h0,'units','points','position',... 
                 [20 30 45 15],'string','brightness','style','text');

hslider=uicontrol('parent',h0,'units','points','position',... 
                  [65 30 120 15],'min',-1,'max',1,'style','slider','callback',...
                  'brighten(get(hslider,''value''))');

%% 建立静态文本框和五个单选按钮 
htext3=uicontrol('parent',h0,'units','points','position',...
                [200 130 80 15],'string','Available Styles:','style','text');

hradio(1)=uicontrol('parent',h0,'units','points','position',...
                    [200 115 80 15],'string','Original','style',...
                    'radiobutton','value',1,'callback',...
                    ['set(hradio,''value'',0);','set(hradio(1),''value'',1);',...
                    'colormap(''default'')']);

hradio(2)=uicontrol('parent',h0,'units','points','position',...
                    [200 100 80 15],'string','Spring','style',...
                    'radiobutton','value',1,'callback',...
                    ['set(hradio,''value'',0);','set(hradio(2),''value'',1);',...
                    'colormap(spring)']);

hradio(3)=uicontrol('parent',h0,'units','points','position',...
                    [200 85 80 15],'string','Summer','style',...
                    'radiobutton','value',1,'callback',...
                    ['set(hradio,''value'',0);','set(hradio(3),''value'',1);',...
                    'colormap(summer)']);

hradio(4)=uicontrol('parent',h0,'units','points','position',...
                    [200 70 80 15],'string','Autumn','style',...
                    'radiobutton','value',1,'callback',...
                    ['set(hradio,''value'',0);','set(hradio(4),''value'',1);',...
                    'colormap(autumn)']);

hradio(5)=uicontrol('parent',h0,'units','points','position',...
                    [200 55 80 15],'string','Winter','style',...
                    'radiobutton','value',1,'callback',...
                    ['set(hradio,''value'',0);','set(hradio(5),''value'',1);',...
                    'colormap(winter)']);

%% 建立关闭图形用户界面按钮【close】
hbutton4=uicontrol('parent',h0,'units','points','string','Close',...    
                   'position',[200 30 50 18],'callback','close');
 
